version: "3"

services:
  reverse-proxy:
    image: traefik
    container_name: traefik
    networks:
      - default
      - traefik
    command: --api --docker
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_NAME}"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  gitlab-ce:
    build: ./gitlab
    restart: on-failure:3
    networks:
      - default
      - traefik
    environment:
      GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://${GITLAB_SUBDOMAIN}.${DOMAIN_NAME}';
          
          unicorn['worker_processes'] = 2;
          
          nginx['listen_port'] = 80;
          nginx['listen_https'] = false;
          nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on"
          }

          registry_external_url 'http://${GITLAB_SUBDOMAIN}.${DOMAIN_NAME}:4567';

          gitlab_rails['omniauth_enabled'] = true 
          gitlab_rails['omniauth_allow_single_sign_on'] = ['idTrustedPlus']
          gitlab_rails['omniauth_block_auto_created_users'] = false

          gitlab_rails['omniauth_providers'] = [
            {
                "name" => "idTrustedPlus",
                "app_id" => "a770658102b887d74112e84bc2476664",
                "app_secret" => "123456",
                "args" => {
                    scope: "userprofile"
                }              
            }
          ]
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitlab"
      - "traefik.frontend.rule=Host:${GITLAB_SUBDOMAIN}.${DOMAIN_NAME}"
      - "traefik.port=80"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.docker.loadbalancer.sticky=true"

    volumes:
      - ./volumes/gitlab-ce/config:/etc/gitlab:Z
      - ./volumes/gitlab-ce/logs:/var/log/gitlab:Z
      - ./volumes/gitlab-ce/data:/var/opt/gitlab:Z

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:latest
  #   container_name: gitlab-runner
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./volumes/gitlab-runner:/etc/gitlab-runner
  #   links:
  #     - gitlab-ce
  #   restart: on-failure:3
  #   networks:
  #       - devops

  # nginx:
  #   build: 
  #     context: ./nginx
  #   container_name: "proxy"
  #   volumes:
  #     - ./volumes/nginx/logs.conf:/var/log/nginx
  #   # links:
  #   #   - gitlab-ce:gitlab-ce
  #     # - gitlab-runner:gitlab-runner
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "22:22"
  #   expose:
  #     - "3000"
  #     - "80"
  #     - "443"
  #     - "22"
  #   environment:
  #     - NGINX_PORT=80
  #     - NGINX_SSL=443
  #     - NGINX_SSL=22
  #   networks:
  #       - devops

  #     # - gitlab-runner:gitlab-runner
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "22:22"
  #   expose:
  #     - "3000"
  #     - "80"
  #     - "443"
  #     - "22"
  #   environment:
  #     - NGINX_PORT=80
  #     - NGINX_SSL=443
  #     - NGINX_SSL=22
  #   networks:
  #       - devops

networks:
  default:
    driver: weavemesh
  traefik:
    external:
      name: public
  
#   devops:
#     driver: bridge