debug = true
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[retry]

[acme]
email = "alm@digt.ru"
storage = "acme.json"
onHostRule = true
onDemand = false
entryPoint = 'https'
    [acme.httpChallenge]
    entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "digt.com"
watch = true
exposedbydefault = false